entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: route53
        delayBeforeCheck: 0

api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic/config.yml
