version: '3.9'

services:
  dnsmasq:
    image: andyshinn/dnsmasq
    container_name: dns
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      devnet:
        ipv4_address: 172.20.0.2
    cap_add:
      - NET_ADMIN

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik:/etc/traefik
      - ./docker/traefik/acme.json:/etc/traefik/acme.json
      - ~/.aws:/root/.aws:ro

    networks:
      - devnet
    depends_on:
      - dnsmasq

  base-image:
    build:
      context: ./base-image
    image: dev-base:latest
    container_name: base-image
    hostname: base-image.docker
    volumes:
      - ~/.ssh/id_rsa.pub:/id_rsa.pub:ro
    networks:
      devnet:
        ipv4_address: 172.20.0.5
    dns:
      - 172.20.0.2

  project1:
    image: dev-base:latest
    container_name: project1
    hostname: project1.docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project1.rule=Host(`project1-local.alistairhenderson.info`)"
      - "traefik.http.routers.project1.entrypoints=websecure"
      - "traefik.http.routers.project1.tls=true"
      - "traefik.http.routers.project1.tls.certresolver=letsencrypt"
    ports:
      - "2221:22"
    networks:
      devnet:
        ipv4_address: 172.20.0.10
    dns:
      - 172.20.0.2
    depends_on:
      - base-image

  project2:
    image: dev-base:latest
    container_name: project2
    hostname: project2.docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project2.rule=Host(`project2-local.alistairhenderson.info`)"
      - "traefik.http.routers.project2.entrypoints=websecure"
      - "traefik.http.routers.project2.tls=true"
      - "traefik.http.routers.project2.tls.certresolver=letsencrypt"
    ports:
      - "2222:22"
    networks:
      devnet:
        ipv4_address: 172.20.0.11
    dns:
      - 172.20.0.2
    depends_on:
      - base-image

  playwright:
    build:
      context: ./playwright-image
    image: dev-playwright:latest
    container_name: playwright
    hostname: playwright.docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.playwright.rule=Host(`playwright-local.alistairhenderson.info`)"
      - "traefik.http.routers.playwright.entrypoints=websecure"
      - "traefik.http.routers.playwright.tls=true"
      - "traefik.http.routers.playwright.tls.certresolver=letsencrypt"
    ports:
      - "2223:22"
    networks:
      devnet:
        ipv4_address: 172.20.0.12
    dns:
      - 172.20.0.2
    depends_on:
      - base-image

networks:
  devnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
